### PR TITLE
Remove keywords from Cargo.toml

### PR DESCRIPTION
**Pull request by jedel1043**
```
error: failed to publish to registry at https://crates.io/
Caused by:
  the remote server responded with an error: expected at most 5 keywords per crate
```

### CODE REVIEW

**Review by nekevss — APPROVED** [review]
Oops, that's my bad. 😅 LGTM

**Comment by jedel1043** [comment]
Also noticed that the categories don't exist on crates.io. Will change that just in case.

**Comment by nekevss** [comment]
Looking at generally similar libraries, "date", "time", "calendar", "timezone", and "duration" might be best.

[Lib.rs](https://lib.rs/search?q=date)

**Comment by jedel1043** [comment]
Yeah, we can publish using those and modify them if needed in the future.

**Review by nekevss — APPROVED** [review]

**Pull request merged**
